-- Registro de cada analisis realizado (RF-14 y RNF-07 del SRS; entidad
-- MetadatoAnalisis del SDD). No guarda la radiografia ni datos del paciente.
CREATE TABLE metadatos_analisis (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    -- Si se elimina la cuenta del medico, el registro de auditoria se conserva.
    usuario_id              VARCHAR(255),
    nombre_archivo          VARCHAR(255)     NOT NULL,
    grado_kl                INTEGER          NOT NULL,
    confianza               DOUBLE PRECISION NOT NULL,
    tiempo_procesamiento_ms BIGINT           NOT NULL,
    -- Clasificador que produjo el resultado ("simulado" mientras no haya modelo real),
    -- para no mezclar pruebas de integracion con resultados del modelo definitivo.
    modelo                  VARCHAR(100)     NOT NULL,
    fecha_creacion          TIMESTAMP        NOT NULL,

    CONSTRAINT pk_metadatos_analisis         PRIMARY KEY (id),
    CONSTRAINT fk_metadatos_analisis_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id) ON DELETE SET NULL,
    CONSTRAINT ck_metadatos_analisis_grado   CHECK (grado_kl BETWEEN 0 AND 4),
    CONSTRAINT ck_metadatos_analisis_conf    CHECK (confianza BETWEEN 0 AND 1)
);

CREATE INDEX ix_metadatos_analisis_usuario ON metadatos_analisis (usuario_id, fecha_creacion);
